### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by sheminanto** [sheminanto/neeto-ui-challenge#7]

**Comment by sheminanto** [comment]
Deployed at [deployed-app-link](https://shemin-neetoui-challenge.herokuapp.com/)
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review

**Comment by yedhink** [comment]
@sheminanto The following error message is too technical. No consumer will be aware what `tags field` even means. Make the message more friendly and compact.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/31244999/190649531-4705ade3-6f43-4514-92d2-a4f897bf1ada.png">


Rest LGTM. Once this change is made, mark this task as completed and go ahead with the next task.
